spring:
  datasource:
    url: jdbc:mysql://localhost:3306/afterCovid
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

  messages:
    basename: messages
#spring.jpa.show-sql: true